name: ds_projek
description: DS PROJEK Automotive - Racing ECU Tuner
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png  # Wajib didaftarkan di sini
